# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(020000)
$foreground = rgb(FCE2D1)
$color0 = rgb(020000)
$color1 = rgb(454039)
$color2 = rgb(454740)
$color3 = rgb(43726F)
$color4 = rgb(437573)
$color5 = rgb(908B80)
$color6 = rgb(F6AD7C)
$color7 = rgb(F2CEB5)
$color8 = rgb(A9907F)
$color9 = rgb(454039)
$color10 = rgb(454740)
$color11 = rgb(43726F)
$color12 = rgb(437573)
$color13 = rgb(908B80)
$color14 = rgb(F6AD7C)
$color15 = rgb(F2CEB5)
