# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2DCD0
background         #181B1E
cursor             #A49A9A

active_tab_foreground     #181B1E
active_tab_background     #E2DCD0
inactive_tab_foreground   #E2DCD0
inactive_tab_background   #181B1E

active_border_color   #E2DCD0
inactive_border_color #181B1E
bell_border_color     #454832

color0      #3F4245
color1		#454832
color2		#655964
color3		#905119
color4		#618DA6
color5		#B2919E
color6		#AD9A78
color7		#CEC4B3
color8		#90897D
color9		#454832
color10		#655964
color11		#905119
color12		#618DA6
color13		#B2919E
color14		#AD9A78
color15		#CEC4B3