# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FCE2D1
background         #020000
cursor             #A09489

active_tab_foreground     #020000
active_tab_background     #FCE2D1
inactive_tab_foreground   #FCE2D1
inactive_tab_background   #020000

active_border_color   #FCE2D1
inactive_border_color #020000
bell_border_color     #454039

color0      #020000
color1		#454039
color2		#454740
color3		#43726F
color4		#437573
color5		#908B80
color6		#F6AD7C
color7		#F2CEB5
color8		#A9907F
color9		#454039
color10		#454740
color11		#43726F
color12		#437573
color13		#908B80
color14		#F6AD7C
color15		#F2CEB5