# =====================================================================
# CÁC LỆNH KHỞI ĐỘNG - EXEC / EXECR
# =====================================================================

# DBus environment variables
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Khởi động lại các systemd services
exec-once = systemctl --user restart xdg-desktop-portal-hyprland xdg-desktop-portal

# Các ứng dụng giao diện nền
exec-once = waybar
exec-once = ibus-daemon -drx --xim --panel=disable
exec-once = swww-daemon
exec-once = swaync


